name: Breaking API

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

jobs:
  breaking-api:
    name: Check for breaking API changes with past release
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release jar
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'
          out-file-path: 'past-releases'

      - name: Check breaking changes
        run: ./gradlew checkBreakingChanges

      - name: Add report to step summary
        run:  cat idofront-catalog-shaded/build/reports/japi.md 2>/dev/null >> $GITHUB_STEP_SUMMARY
