name: Publish

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - examples
      - docs

jobs:
  publish:
    name: Check and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # TODO maybe split MIA action into a setup and run one since we keep needing to run actions between them?
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      # TODO disabled until we figure out a nice PR workflow for warning about breaking changes
      #      - uses: ./.github/actions/breaking-changes
      #        continue-on-error: true # TODO eventually hard fail when a release detects breaking changes without a MAJOR bump, allow on ${{ env.IS_SNAPSHOT }}

      - uses: MineInAbyss/publish-action@v3
        with:
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
          pre-build: './gradlew versionInfo'
          changelog-prefix-file: "build/versions.md"
          skip-java-setup: true # We already setup earlier
          build-tasks: 'build publish'
          release-files: |
            ${{ github.workspace }}/publish/*.jar
