name: Publish

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - uses: .github/workflows/breaking-api.yml
        continue-on-error: true # TODO eventually hard fail when a release detects breaking changes without a MAJOR bump, allow on ${{ env.IS_SNAPSHOT }}

      - uses: MineInAbyss/publish-action@develop
        with:
          maven-metadata-url: https://repo.mineinabyss.com/releases/com/mineinabyss/idofront-util/maven-metadata.xml
          maven-snapshot-metadata-url: https://repo.mineinabyss.com/snapshots/com/mineinabyss/idofront-util/maven-metadata.xml
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
          release-files: |
            ${{ github.workspace }}/publish/*.jar
